# Generated by Django 4.2.30 on 2026-04-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('risk_level', models.CharField(max_length=50)),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('returns_3yr', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('returns_5yr', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('expense_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fund_size', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fund_manager', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.CharField(db_index=True, max_length=100)),
                ('rating', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('query', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('response_id', 'session_id')},
            },
        ),
    ]
